"""init tables

Revision ID: 72379f22d2bc
Revises: 
Create Date: 2026-02-19 23:10:25.920307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72379f22d2bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_job',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('video_asset',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['video_job.job_id'], ),
    sa.PrimaryKeyConstraint('video_id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_asset')
    op.drop_table('video_job')
    # ### end Alembic commands ###
