"""initial schema

Revision ID: ca206296f848
Revises: 
Create Date: 2026-02-22 23:50:24.484935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca206296f848'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_job',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_video_job_job_id'), 'video_job', ['job_id'], unique=False)
    op.create_table('narrative',
    sa.Column('narrative_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=False),
    sa.Column('full_story', sa.Text(), nullable=False),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['video_job.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('narrative_id')
    )
    op.create_index(op.f('ix_narrative_job_id'), 'narrative', ['job_id'], unique=True)
    op.create_table('scene',
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['video_job.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_id')
    )
    op.create_index(op.f('ix_scene_job_id'), 'scene', ['job_id'], unique=False)
    op.create_index('ix_scene_job_start', 'scene', ['job_id', 'start_sec'], unique=False)
    op.create_table('snapshot',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('timestamp_sec', sa.Float(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['video_job.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('job_id', 'timestamp_sec', name='uq_snapshot_job_timestamp')
    )
    op.create_index(op.f('ix_snapshot_job_id'), 'snapshot', ['job_id'], unique=False)
    op.create_index('ix_snapshot_job_time', 'snapshot', ['job_id', 'timestamp_sec'], unique=False)
    op.create_table('snapshot_config',
    sa.Column('config_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('sampling_fps', sa.Float(), nullable=False),
    sa.Column('chunk_length_sec', sa.Integer(), nullable=False),
    sa.Column('resize_width', sa.Integer(), nullable=True),
    sa.Column('grayscale', sa.Boolean(), nullable=False),
    sa.Column('black_white', sa.Boolean(), nullable=False),
    sa.Column('image_format', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['video_job.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index(op.f('ix_snapshot_config_job_id'), 'snapshot_config', ['job_id'], unique=True)
    op.create_table('video_asset',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['video_job.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index(op.f('ix_video_asset_job_id'), 'video_asset', ['job_id'], unique=True)
    op.create_table('scene_snapshot',
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.scene_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_id', 'snapshot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene_snapshot')
    op.drop_index(op.f('ix_video_asset_job_id'), table_name='video_asset')
    op.drop_table('video_asset')
    op.drop_index(op.f('ix_snapshot_config_job_id'), table_name='snapshot_config')
    op.drop_table('snapshot_config')
    op.drop_index('ix_snapshot_job_time', table_name='snapshot')
    op.drop_index(op.f('ix_snapshot_job_id'), table_name='snapshot')
    op.drop_table('snapshot')
    op.drop_index('ix_scene_job_start', table_name='scene')
    op.drop_index(op.f('ix_scene_job_id'), table_name='scene')
    op.drop_table('scene')
    op.drop_index(op.f('ix_narrative_job_id'), table_name='narrative')
    op.drop_table('narrative')
    op.drop_index(op.f('ix_video_job_job_id'), table_name='video_job')
    op.drop_table('video_job')
    # ### end Alembic commands ###
